# Generated by Django 3.2 on 2021-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=20, verbose_name='Dataset name')),
                ('phenotype', models.CharField(max_length=255, verbose_name='Phenotype')),
                ('accuracy', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Accuracy')),
                ('accuracy_sd', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Accuracy SD')),
                ('f1_score', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='F1Score')),
                ('f1_score_sd', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='F1Score SD')),
            ],
            options={
                'verbose_name_plural': 'Metrics',
                'ordering': ['-dataset', '-accuracy', '-f1_score'],
            },
        ),
    ]
