# Generated by Django 3.2 on 2021-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.CharField(max_length=20, verbose_name='Execution')),
                ('grammar', models.CharField(max_length=20, verbose_name='Grammar name')),
                ('dataset', models.CharField(max_length=20, verbose_name='Dataset name')),
                ('generation', models.IntegerField(verbose_name='Generation')),
                ('phenotype', models.TextField(verbose_name='Phenotype')),
                ('accuracy', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='Accuracy')),
                ('f1_score', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='F1Score')),
                ('num_layers', models.IntegerField(verbose_name='Num. layers')),
                ('num_params', models.IntegerField(verbose_name='Num. params')),
                ('time', models.DecimalField(decimal_places=6, max_digits=22, verbose_name='Training time')),
            ],
            options={
                'verbose_name_plural': 'Steps',
                'ordering': ['-execution', '-generation'],
            },
        ),
    ]
