# Generated by Django 3.2 on 2021-05-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='accuracy',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='accuracy_sd',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='Accuracy SD'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='f1_score',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='F1Score'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='f1_score_sd',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='F1Score SD'),
        ),
    ]
