# Generated by Django 3.2 on 2021-10-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='num_layers',
        ),
        migrations.RemoveField(
            model_name='step',
            name='num_params',
        ),
    ]
