# Generated by Django 3.2 on 2021-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_metric_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='dataset',
            field=models.CharField(max_length=20, verbose_name='Dataset name'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='phenotype',
            field=models.TextField(verbose_name='Phenotype'),
        ),
    ]
