# Generated by Django 3.2 on 2021-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_metric_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('TRAINING', 'TRAINING'), ('TRAINED', 'TRAINED')], default='NEW', max_length=10, verbose_name='Status'),
        ),
    ]
